name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  publish-docker:
    uses: ./.github/workflows/publish-docker.yml
    secrets:
      DENO_AUTH_TOKENS: ${{ secrets.DENO_AUTH_TOKENS }}

  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    secrets:
      DOCKER_REGISTRY_TOKEN:            ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      SSH_PRIVATE_KEY:                  ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS:                  ${{ secrets.SSH_KNOWN_HOSTS }}
      PRODUCTION_ENCRYPT_KEY:           ${{ secrets.PRODUCTION_ENCRYPT_KEY }}
      PRODUCTION_SIGNING_KEY:           ${{ secrets.PRODUCTION_SIGNING_KEY }}
      PRODUCTION_DATABASE_URL:          ${{ secrets.PRODUCTION_DATABASE_URL }}
      PRODUCTION_REDIS_CACHE_URL:       ${{ secrets.PRODUCTION_REDIS_CACHE_URL }}
      PRODUCTION_REDIS_WORKERS_URL:     ${{ secrets.PRODUCTION_REDIS_WORKERS_URL }}
      PRODUCTION_GITHUB_CLIENT_ID:      ${{ secrets.PRODUCTION_GITHUB_CLIENT_ID }}
      PRODUCTION_GITHUB_CLIENT_SECRET:  ${{ secrets.PRODUCTION_GITHUB_CLIENT_SECRET }}
      PRODUCTION_GITHUB_ACCESS_TOKEN:   ${{ secrets.PRODUCTION_GITHUB_ACCESS_TOKEN }}
      PRODUCTION_DISCORD_CLIENT_ID:     ${{ secrets.PRODUCTION_DISCORD_CLIENT_ID }}
      PRODUCTION_DISCORD_CLIENT_SECRET: ${{ secrets.PRODUCTION_DISCORD_CLIENT_SECRET }}
      PRODUCTION_AWS_ACCESS_KEY_ID:     ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
      PRODUCTION_AWS_SECRET_KEY:        ${{ secrets.PRODUCTION_AWS_SECRET_KEY }}
      PRODUCTION_POSTMARK_API_TOKEN:    ${{ secrets.PRODUCTION_POSTMARK_API_TOKEN }}
      PRODUCTION_PAPERTRAIL_TOKEN:      ${{ secrets.PRODUCTION_PAPERTRAIL_TOKEN }}
    needs:
      - publish-docker
